package org.hddframework.generator.ui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import org.apache.commons.lang3.StringUtils;
import org.hddframework.generator.mybatis.MybatisGenerator;
import org.hddframework.generator.mybatis.configuration.*;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.Objects;
import java.util.concurrent.BrokenBarrierException;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.CyclicBarrier;

/**
 * @author SongWei
 */
public class ProjectGeneratorJFrame extends JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ProjectGeneratorJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {


        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox13 = new javax.swing.JCheckBox();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();

        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jProgressBar1 = new javax.swing.JProgressBar();
        jTextField6.setEditable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("ProjectGenerator"); // NOI18N
        setTitle("SimpleProjectGenerator");

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Gradle");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Maven");

        jLabel1.setText("选择目录:");

        jLabel2.setText("基础包名:");

        jLabel3.setText("数据库连接URL:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"MYSQL", "PostgreSQL", "SQLSERVER", "DB2", "ORACL", "SYBASE"}));
        jComboBox1.setSelectedItem(0);

        jLabel4.setText("数据库连接驱动:");

        jLabel5.setText("数据库用户名:");

        jLabel6.setText("数据库密码:");

        jLabel7.setText("设置表规则:");

        jLabel8.setText("选择构建方式:");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("生成Controller");

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("生成Service");

        jCheckBox3.setSelected(true);
        jCheckBox3.setText("生成ServiceImpl");

        jCheckBox4.setSelected(true);
        jCheckBox4.setText("生成DataSource");

        jCheckBox5.setSelected(true);
        jCheckBox5.setText("生成Mapper");

        jCheckBox6.setSelected(true);
        jCheckBox6.setText("生成MapperXml");

        jCheckBox7.setSelected(true);
        jCheckBox7.setText("生成Model");

        jCheckBox8.setSelected(true);
        jCheckBox8.setText("生成ModelExample");

        jCheckBox9.setSelected(true);
        jCheckBox9.setText("生成MybatisCriterion");

        jCheckBox10.setSelected(true);
        jCheckBox10.setText("生成PropertiesFile");

        jCheckBox11.setSelected(true);
        jCheckBox11.setText("生成StartupFile");

        jCheckBox12.setSelected(true);
        jCheckBox12.setText("生成BuildFile");

        jButton1.setText("生成项目");

        jButton2.setText("重置所有");

        jLabel9.setText("是否启用下划线驼峰映射:");

        jCheckBox13.setSelected(true);

        jButton3.setText("选择目录");

        jLabel10.setText("设置不包含表:");

        jTextField7.setToolTipText("多表使用逗号分隔");

        jCheckBox14.setText("生成WebMvcConfig");
        jCheckBox15.setText("生成ExceptionHandler");
        jCheckBox16.setText("生成通用ResultData");
        jCheckBox14.setSelected(true);
        jCheckBox15.setSelected(true);
        jCheckBox16.setSelected(true);

        jProgressBar1.setSize(new java.awt.Dimension(140, 16));

        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                jButton1.setEnabled(false);
                // System.out.println("1" + jTextField1.getText()); // 包名
                // System.out.println("2" + jTextField2.getText()); //URL
                // System.out.println("3" + jTextField3.getText()); //数据库用户
                // System.out.println("4" + jTextField4.getText()); // 数据库密码
                // System.out.println("5" + jTextField5.getText()); //表规则
                // System.out.println("6" + jTextField6.getText()); // 项目目录

                // System.out.println(jRadioButton1.isSelected());
                // System.out.println(jRadioButton2.isSelected());
                // System.out.println(jCheckBox13.isSelected());
                // System.out.println(jComboBox1.getSelectedItem());
                // System.out.println(jCheckBox1.isSelected()); // controller
                // System.out.println(jCheckBox2.isSelected()); // service
                // System.out.println(jCheckBox3.isSelected());  // serviceImpl
                // System.out.println(jCheckBox4.isSelected()); //datasource
                // System.out.println(jCheckBox5.isSelected());  // mapper
                // System.out.println(jCheckBox6.isSelected()); // mapperxml
                // System.out.println(jCheckBox7.isSelected()); // model
                // System.out.println(jCheckBox8.isSelected()); //modelExample
                // System.out.println(jCheckBox9.isSelected()); // plugin criterion
                // System.out.println(jCheckBox10.isSelected()); // Properties
                // System.out.println(jCheckBox11.isSelected()); // startupfile
                // System.out.println(jCheckBox12.isSelected()); // buildfile
                // System.out.println(jCheckBox14.isSelected()); // webMvcConfig
                // System.out.println(jCheckBox15.isSelected()); // exceptionHandlerConfig
                // System.out.println(jCheckBox16.isSelected()); // commonResultData

                ButtonModel buttonModel = buttonGroup1.getSelection();
                buttonModel.getSelectedObjects();

                MBGConfiguration mbgConfiguration = new MBGConfiguration();

                DatabaseConfiguration databaseConfiguration = new DatabaseConfiguration();
                // "MYSQL", "PostgreSQL", "SQLSERVER", "DB2", "ORACL", "SYBASE"
                String driveClass = "";
                String url = jTextField2.getText();
                if ("MYSQL".equalsIgnoreCase(jComboBox1.getSelectedItem().toString())) {
                    driveClass = "com.mysql.cj.jdbc.Driver";
                    if (StringUtils.isNoneBlank(url)) {
                        if (!url.contains("?")) {
                            url = url + "?";
                        } else {
                            url = url + "&";
                        }
                        if (!url.contains("zeroDateTimeBehavior")) {
                            url = url + "zeroDateTimeBehavior=CONVERT_TO_NULL";
                        }
                        url = url.replaceAll("&&", "&").replaceAll("\\?", "?");
                    }
                    // zeroDateTimeBehavior=CONVERT_TO_NULL
                }
                if ("PostgreSQL".equalsIgnoreCase(jComboBox1.getSelectedItem().toString())) {
                    driveClass = "org.postgresql.Driver";
                }
                System.out.println("driveClass: " + driveClass);
                databaseConfiguration.setDriverClassName(driveClass);
                databaseConfiguration.setUrl(url);
                databaseConfiguration.setUserName(jTextField3.getText());
                databaseConfiguration.setPassword(StringUtils.isBlank(jTextField4.getText()) ? "" : jTextField4.getText());
                databaseConfiguration.setTableNamePattern(StringUtils.isBlank(jTextField5.getText()) ? "" : jTextField5.getText());
                String excludeTableStr = jTextField7.getText();
                if (StringUtils.isNotBlank(excludeTableStr)) {
                    String[] excludeTable = excludeTableStr.split(",");
                    databaseConfiguration.setExcludeTable(excludeTable);
                }

                GenerationConfiguration generationConfiguration = new GenerationConfiguration();
                generationConfiguration.setMapUnderscoreToCamelCase(jCheckBox13.isSelected());

                ProjectConfiguration projectConfiguration = new ProjectConfiguration();
                projectConfiguration.setRootAbsolutePath(jTextField6.getText());
                projectConfiguration.setRootPackageName(jTextField1.getText());
                projectConfiguration.setUseMaven(jRadioButton2.isSelected());

                GeneratorConfiguration generatorConfiguration = new GeneratorConfiguration();

                generatorConfiguration.setGenerateBuildFile(jCheckBox12.isSelected());
                generatorConfiguration.setGenerateProjectPropertiesFile(jCheckBox10.isSelected());
                generatorConfiguration.setGenerateDataSourceConfigurationFile(jCheckBox4.isSelected());
                generatorConfiguration.setGenerateMybatisCriterion(jCheckBox9.isSelected());
                generatorConfiguration.setGenerateController(jCheckBox1.isSelected());
                generatorConfiguration.setGenerateMapper(jCheckBox5.isSelected());
                generatorConfiguration.setGenerateMapperXml(jCheckBox6.isSelected());
                generatorConfiguration.setGenerateModel(jCheckBox7.isSelected());
                generatorConfiguration.setGenerateModelExample(jCheckBox8.isSelected());
                generatorConfiguration.setGenerateService(jCheckBox2.isSelected());
                generatorConfiguration.setGenerateServiceImpl(jCheckBox3.isSelected());
                generatorConfiguration.setGenerateStartupFile(jCheckBox11.isSelected());

                generatorConfiguration.setGenerateWebMvcConfiguration(jCheckBox14.isSelected());
                generatorConfiguration.setGenerateExceptionHandler(jCheckBox15.isSelected());
                generatorConfiguration.setGenerateResultData(jCheckBox16.isSelected());

                mbgConfiguration.setDatabaseConfiguration(databaseConfiguration);
                mbgConfiguration.setGenerationConfiguration(generationConfiguration);
                mbgConfiguration.setProjectConfiguration(projectConfiguration);

                mbgConfiguration.setGeneratorConfiguration(generatorConfiguration);

                MybatisGenerator generator = new MybatisGenerator(mbgConfiguration);

                CyclicBarrier cyclicBarrier = new CyclicBarrier(2, new Runnable() {
                    @Override
                    public void run() {
                        jButton1.setEnabled(true);
                    }
                });
                new Thread() {
                    @Override
                    public void run() {
                        try {
                            generator.generateFile();
                        } catch (Exception e) {
                            e.printStackTrace();
                            jButton1.setEnabled(true);
                        }
                        try {
                            cyclicBarrier.await();
                        } catch (InterruptedException | BrokenBarrierException e) {
                            e.printStackTrace();
                            jButton1.setEnabled(true);
                        }
                    }
                }.start();
                jProgressBar1.setStringPainted(true);
                new Thread() {
                    public void run() {
                        for (int i = 0; i <= 100; i++) {
                            try {
                                Thread.sleep(60);
                            } catch (InterruptedException e) {
                                e.printStackTrace();
                                jButton1.setEnabled(true);
                            }
                            jProgressBar1.setValue(i);
                        }
                        try {
                            cyclicBarrier.await();
                        } catch (InterruptedException | BrokenBarrierException e) {
                            e.printStackTrace();
                            jButton1.setEnabled(true);
                        }
                        jProgressBar1.setString("Generate Success");
                    }
                }.start();

            }
        });


        jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jCheckBox1.setSelected(true);
                jCheckBox2.setSelected(true);
                jCheckBox3.setSelected(true);
                jCheckBox4.setSelected(true);
                jCheckBox5.setSelected(true);
                jCheckBox6.setSelected(true);
                jCheckBox7.setSelected(true);
                jCheckBox8.setSelected(true);
                jCheckBox9.setSelected(true);
                jCheckBox10.setSelected(true);
                jCheckBox11.setSelected(true);
                jCheckBox12.setSelected(true);
                jCheckBox13.setSelected(true);
                jCheckBox14.setSelected(true);
                jCheckBox15.setSelected(true);
                jCheckBox16.setSelected(true);

                jRadioButton1.setSelected(true);

                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jProgressBar1.setString("");

                jComboBox1.setSelectedIndex(0);
            }
        });

        jButton3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFileChooser jfc = new JFileChooser();
                jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
                jfc.showDialog(new JLabel(), "Confirm");
                File file = jfc.getSelectedFile();
                if (Objects.nonNull(file)) {
                    if (file.isDirectory()) {
//                        System.out.println("文件夹:" + file.getAbsolutePath());
                        jTextField6.setText(file.getAbsolutePath());

                    } else if (file.isFile()) {
//                        System.out.println("文件:" + file.getAbsolutePath());
                    }
//                    System.out.println(jfc.getSelectedFile().getName());
//                    jTextField6.setText(file.getAbsolutePath());
                }

            }
        });


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(35, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jButton2)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton1))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel5)
                                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(31, 31, 31)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jLabel6))
                                                                        .addComponent(jTextField5))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGap(113, 113, 113)
                                                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jButton3))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(jCheckBox9)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jCheckBox10)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jCheckBox11)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jCheckBox12))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel1)
                                                                                        .addComponent(jLabel2))
                                                                                .addGap(57, 57, 57)
                                                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jCheckBox16))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jCheckBox1)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jCheckBox2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jCheckBox3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jCheckBox4)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jCheckBox14))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel8)
                                                                .addGap(25, 25, 25)
                                                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel9)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jCheckBox13))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jCheckBox5)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jCheckBox6)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jCheckBox7)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jCheckBox8)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jCheckBox15))))
                                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(55, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{jCheckBox1, jCheckBox10, jCheckBox11, jCheckBox12, jCheckBox14, jCheckBox15, jCheckBox16, jCheckBox2, jCheckBox3, jCheckBox4, jCheckBox5, jCheckBox6, jCheckBox7, jCheckBox8, jCheckBox9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{jButton1, jButton2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{jTextField3, jTextField4});

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBox13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jRadioButton1)
                                                .addComponent(jRadioButton2)
                                                .addComponent(jLabel9)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jCheckBox1)
                                        .addComponent(jCheckBox2)
                                        .addComponent(jCheckBox3)
                                        .addComponent(jCheckBox4)
                                        .addComponent(jCheckBox14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jCheckBox5)
                                        .addComponent(jCheckBox6)
                                        .addComponent(jCheckBox7)
                                        .addComponent(jCheckBox8)
                                        .addComponent(jCheckBox15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jCheckBox9)
                                        .addComponent(jCheckBox10)
                                        .addComponent(jCheckBox11)
                                        .addComponent(jCheckBox12)
                                        .addComponent(jCheckBox16))
                                .addGap(17, 17, 17)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(jButton2))
                                .addGap(23, 23, 23))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]{jCheckBox1, jCheckBox10, jCheckBox11, jCheckBox12, jCheckBox14, jCheckBox15, jCheckBox16, jCheckBox2, jCheckBox3, jCheckBox4, jCheckBox5, jCheckBox6, jCheckBox7, jCheckBox8, jCheckBox9});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]{jTextField1, jTextField2, jTextField5, jTextField6});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]{jButton1, jButton2});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]{jTextField3, jTextField4});

        pack();
    }// </editor-fold>

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new NewJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration
}

